version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker
      - run: apk add bash

      - run:
          name: Determine effective build tag.
          command: |
            # If the branch being built contains a slash `prefix/`, use that
            # `prefix` as the tag for the cached continuous integration image.
            CI_CACHE_TAG=${CIRCLE_BRANCH%/*}
            if [[ $CI_CACHE_TAG == $CIRCLE_BRANCH ]]; then
              CI_CACHE_TAG="latest"
            fi

            docker pull liveramp/gazette-ci-cache:${CI_CACHE_TAG}




      # Determine the effective tag for this build.
      # Prefer

      - checkout

      # Pull down current vendor cache.
      - run: ./v2/build/all.sh

      - run:
          name: Push V2 Gazette.
          command: |
            export TAG=2.0.${CIRCLE_BUILD_NUM}
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_LOGIN --password-stdin
            ./v2/build/push.sh ${TAG}
